name: Tallyfy Answers Workflow

on:
  workflow_run:
    workflows: ["Tallyfy Answers - Generate IDs"]
    types:
      - completed


jobs:
  validate-markdown:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Markdown Lint Script
        run: |
          python -m pip install --upgrade pyyaml
          python scripts/markdown-lint.py --dir=$PWD
        shell: bash
    outputs:
      validate-markdown-completed: ${{ steps.validate-markdown.outcome }}

  generate-snippets:
    needs: validate-markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate snippets script
        run: |
          file_changes=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r ${{ github.sha }} | grep '\.mdx$' || true )
          if [[ -n "$file_changes" ]]; then
            git pull
            python -m pip install --upgrade python-frontmatter requests
            python scripts/generate-snippets.py --dir=$PWD --files="$file_changes" --token ${{ secrets.CLAUDE_API_KEY }} --prompt ${{ secrets.CLAUDE_PROMPT }}
          else
            echo "No new files added. Skipping snippet generation."
          fi
        shell: bash
      - name: Commit and push articles with snippets
        run: |
          file_changes=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r ${{ github.sha }} | grep '\.mdx$' || true )
          if [[ -n "$file_changes" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git add .
            git commit -m "Push Articles With snippet(s)" -a
            git push
          else
            echo "No files changed. Skipping snippet generation."
          fi
    outputs:
      generate-snippets-completed: ${{ steps.generate-snippets.outcome }}

  upload-to-tallyfy-answers:
    needs: generate-snippets
#    needs: validate-markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Dump articles into JSON file
        run: |
          git pull
          python -m pip install --upgrade python-frontmatter requests
          python scripts/answers-connector.py --dir=$PWD/src/content/docs --collection_name=tyfy --answers_api_key=${{ secrets.ANSWERS_API_KEY }}
        shell: bash
    outputs:
      upload-to-tallyfy-answers-completed: ${{ steps.upload-to-tallyfy-answers.outcome }}

  check-deleted-files:
    needs: upload-to-tallyfy-answers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check deleted files
        run: |
          file_changes=$(git diff-tree --no-commit-id --name-only --diff-filter=D -r ${{ github.sha }} | grep '\.mdx$' || true )
          if [[ -n "$file_changes" ]]; then
            python -m pip install --upgrade python-frontmatter requests
            python scripts/check-deleted-files.py --commit_sha=${{ github.sha }} --collection_name=tyfy --github_token=${{ secrets.GH_TOKEN }} --answers_api_key=${{ secrets.ANSWERS_API_KEY }}
          else
            echo "No files were deleted. Skipping ..."
          fi


  update-last-modified:
    needs: upload-to-tallyfy-answers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate Git dates
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update lastUpdated dates from Git history
        run: |
          git pull
          python -m pip install --upgrade python-frontmatter
          python scripts/update-last-modified.py --dir=src/content/docs
        shell: bash
      - name: Commit and push lastUpdated dates
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update lastUpdated dates from Git history" -a
            git pull
            git push
          else
            echo "No lastUpdated changes needed"
          fi

  generate-related-articles:
    needs: upload-to-tallyfy-answers
    #    if: needs.upload-to-tallyfy-search.outputs.upload-to-tallyfy-search-completed == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate related articles script
        run: |
          git pull
          python -m pip install --upgrade python-frontmatter requests
          python scripts/generate-related-articles.py --dir=$PWD/src/content/docs --answers_api_key=${{ secrets.ANSWERS_API_KEY }}
        shell: bash
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Push related articles" -a
          git pull
          git push

  sync:
    needs: [ validate-markdown, upload-to-tallyfy-answers, check-deleted-files, update-last-modified, generate-related-articles ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (tallyfy/documentation)
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout target repository (tallyfy/support-docs)
        uses: actions/checkout@v3
        with:
          repository: tallyfy/support-docs
          token: ${{ secrets.GH_TOKEN }}
          path: target-repo

      - name: Sync files
        run: |
          rsync -av --delete src/content/docs/ target-repo/src/content/docs/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add src/content/docs
          git commit -m "Sync docs from tallyfy/documentation"
          git push --set-upstream origin HEAD
