name: Sync Support Docs

on:
  workflow_run:
    workflows: ["Tallyfy Answers Workflow"]
    types:
      - completed
    branches:
      - main
    conclusion: success

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (tallyfy/documentation)
        uses: actions/checkout@v3

      - name: Checkout target repository (tallyfy/support-docs)
        uses: actions/checkout@v3
        with:
          repository: tallyfy/support-docs
          token: ${{ secrets.GH_TOKEN }}
          path: target-repo

      - name: Sync files
        run: |
          rsync -av --delete src/content/docs/ target-repo/src/content/docs/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add src/content/docs
          git commit -m "Sync docs from tallyfy/documentation"
          git push --set-upstream origin HEAD